lakehouse_trino:
  target: stg
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      password: ""
      host: localhost
      port: 8080
      database: iceberg
      schema: retail_gold
      threads: 4
      client_tags: ["dbt", "lakehouse"]
    stg:
      type: trino
      method: none
      user: admin
      password: ""
      host: localhost
      port: 8080
      database: iceberg_stg
      schema: stg_gold
      threads: 4
      client_tags: ["dbt", "iceberg_stg"]
